### ISSUE TITLE
Send meme back to chat with meme_manager_bot

### ISSUE THREAD

**Issue by lisasedova** [imbananko/tilly#87]
Все мемы, отправленные в meme_manager_bot, дублируются с зеркалирование клавиатуры из чата и канала в личку с meme_manager_bot.
При этом оригинал мама (сама картинка) удаляется.

**Comment by imbananko** [comment]
мать не трогай

**Comment by yeplastun** [comment]
Мать святое

**Comment by imbananko** [comment]
#95

**Comment by imbananko** [comment]
implemented
