### ISSUE TITLE
/help

### ISSUE THREAD

**Issue by lisasedova** [imbananko/tilly#98]
1. После сообщения /help в меме-менеджер, он должен отвечать текстом:

"Привет, я @meme_manager. Чат со мной - для твоих лучших мемов, которыми охота поделиться. 

Отправь самый крутой мем, и если он пройдёт модерацию - попадёт в канал «Че с деньгами». Мем, набравший за неделю больше всех кристаллов, станет мемом недели, а его обладатель получит признание и поздравление на канале.

**Термины и определения:**

**Мем** (англ. meme) — единица культурной информации, имеющей развлекательный характер (в нашем случае - картинка).

**Модерация** (от лат. moderor — умеряю, сдерживаю) — все мемы проходят предварительную оценку экспертов, а на канал попадут только лучшие. За динамикой оценки также можно следить тут.”

\+ картинка (перед текстом):
![IMAGE 2020-02-15 17:12:00](https://user-images.githubusercontent.com/60506298/74589423-4aa43700-5016-11ea-8d0e-0a10a5a00e32.jpg)

2. Этот же текст меме-менеджер однократно публикует на канал.

**Comment by yeplastun** [comment]
@lisasedova так все таки /help или /info?

**Comment by lisasedova** [comment]
/help. Поправила выше
